<?php

require_once 'HighWay.php';

class ResidentialWay extends HighWay
{
    public function addVehicle($vehicle)
    {
        $this->currentVehicle = $vehicle;

        // TODO: Implement addVehicle() method.
    }

    public function setNbLane($nbLane)
    {
        parent::setNbLane($nbLane); // TODO: Change the autogenerated stub
        $this->setNbLane(2);
    }

    public function setMaxSpeed($maxSpeed)
    {
        parent::setMaxSpeed($maxSpeed); // TODO: Change the autogenerated stub
        $this->setMaxSpeed(50);
    }

}